[Rust] Supported new C-APIs (#1732)
* [CI][refactor](bindings-rust): Added new trigger condition.
* [CI][refactor](inventory): Added new trigger condition.
* [Rust][feat](vm): Implemented new APIs.
* [Rust][refactor](vm): Refactored test code.
* [Rust SDK][refactor](executor): Refactored test code.
* [Rust SDK][feat](vm, lib): Implemented Engine trait for Vm.
* [Rust SDK][version]: v0.3.1
* [Rust][version]: v0.8.1
* [Rust][feat](utils): Implemented driver functions.
* [Rust SDK][feat](lib, utils): Added utils module and implemented driver functions.
* [CI][refactor](rust): Refactored rust-release-related workflows.
* [Rust][feat](module): Implemented WasiNnModule.
* [Rust][feat](module, lib): Implemented WasiCryptoCommon and WasiCryptoAsymmetricCommon.
* [Rust][feat](module, lib): Implemented WasiCryptoSymmetric.
* [Rust][feat](module, lib): Implemented WasiCryptoKx.
* [Rust][feat](module, lib): Implemented WasiCryptoSignature.
* [Rust][refactor](module, lib): Renamed WasiCryptoSignatures.
* [Rust][refactor](module): Refactored name functions.
* [Rust][refactor](module, vm): Refactored name functions.
* [Rust][refactor](module, executor, vm): Refactored AsImport trait.
* [Rust SDK][feat](import): Supported for building wasi-nn and wasi-crypto import objects.
* [Rust SDK][feat](instance): Defined AsInstance trait and implemented WasiNnInstance.
* [Rust SDK][feat](instance, lib, vm): Implemented wasi-nn and wasi-crypto instances.
* [Rust SDK][feat](instance): Implemented AsInstance trait for WasmEdgeProcessInstance.
* [Rust SDK][refactor](instance, wasi): Moved wasi related types into wasi module.
* [Rust SDK][refactor](lib): Exposed the types defined in wasmedge-types crate.
* [Rust SDK][fix](instance): Fixed an import issue.
* [Rust SDK][fix](instance): Fixed clippy issues.
* [CI][fix](rust): Fixed review issues.
* [CI][fix](rust): Fix a review issue.

Signed-off-by: Xin Liu <sam@secondstate.io>

diff --git a/.github/workflows/inventory.yml b/.github/workflows/inventory.yml
--- a/.github/workflows/inventory.yml
+++ b/.github/workflows/inventory.yml
@@ -8,15 +8,16 @@ on:
   push:
     branches:
       - master
+      - "rust/*"
     paths:
       - ".github/workflows/inventory.yml"
-      - 'bindings/rust/wasmedge-sys/**'
+      - "bindings/rust/wasmedge-sys/**"
   pull_request:
     branches:
       - master
     paths:
       - ".github/workflows/inventory.yml"
-      - 'bindings/rust/wasmedge-sys/**'
+      - "bindings/rust/wasmedge-sys/**"
 
 jobs:
   rust:
@@ -25,19 +26,19 @@ jobs:
       image: wasmedge/wasmedge:ubuntu-build-clang
 
     steps:
-    - uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
 
-    - name: Install dependency
-      run: |
-        apt update
-        apt install -y ctags
+      - name: Install dependency
+        run: |
+          apt update
+          apt install -y ctags
 
-    - name: Inventory for rust-sys
-      run: |
-        for fn in `ctags -x --c-types=f+p include/api/wasmedge/wasmedge.h  | awk '/^WasmEdge_/{print $1}'`; do
-          grep -q ${fn} -R bindings/rust/wasmedge-sys || echo "${fn} is not used in rust-sys crate" >> /tmp/missing_api_in_rust.txt
-        done;
-        cat /tmp/missing_api_in_rust.txt || exit 0
-        exit `wc -l /tmp/missing_api_in_rust.txt | awk '{print $1}'`
+      - name: Inventory for rust-sys
+        run: |
+          for fn in `ctags -x --c-types=f+p include/api/wasmedge/wasmedge.h  | awk '/^WasmEdge_/{print $1}'`; do
+            grep -q ${fn} -R bindings/rust/wasmedge-sys || echo "${fn} is not used in rust-sys crate" >> /tmp/missing_api_in_rust.txt
+          done;
+          cat /tmp/missing_api_in_rust.txt || exit 0
+          exit `wc -l /tmp/missing_api_in_rust.txt | awk '{print $1}'`
