[Utils] Installer Script: Tweak sort version sort for better semantic sorting. Fix #1501 (#1506)
* [utils] Installer Script: Tweak sort version sort for better semantic sorting
  * Fix #1501
* [Utils] Installer Script: Fix macOS sed error
  * Used awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' instead of sed '/-/!{s/$/_/}'
* [CI] Installer Script: Add version dependent test points
* [CI] fix: Invalid Workflow file
* [CI] fix: Workflow fail

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

diff --git a/.github/workflows/test-install-script.yml b/.github/workflows/test-install-script.yml
--- a/.github/workflows/test-install-script.yml
+++ b/.github/workflows/test-install-script.yml
@@ -143,6 +143,70 @@ jobs:
         ls ~/new_wasmedge/plugin/ | grep .so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
         bash utils/install.sh -v 0.10.0-alpha.1 -p /usr
         ls /usr/lib/wasmedge/ | grep libwasmedgePluginWasmEdgeProcess.so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+    - name: Image Extensions - Version Based Conditions check
+      run: |
+        VERSION_IM_DEPS=0.9.1
+        # arch64
+        [ "$(printf %s\\n%s\\n "0.9.1-beta.1" "$VERSION_IM_DEPS")" != "$(printf %s\\n%s "0.9.1-beta.1" "$VERSION_IM_DEPS" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          (echo "Fail: Sort failed" && exit 1) || echo "Pass: Extensions Compatible"
+        
+        VERSION_IM_DEPS=0.9.1-rc.1
+        # arch64
+        [ "$(printf %s\\n%s\\n "0.9.1-beta.1" "$VERSION_IM_DEPS")" != "$(printf %s\\n%s "0.9.1-beta.1" "$VERSION_IM_DEPS" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          (echo "Fail: Sort failed" && exit 1) || echo "Pass: Extensions Compatible"
+        
+        VERSION_IM_DEPS=0.9.1-beta.2
+        # arch64
+        [ "$(printf %s\\n%s\\n "0.9.1-beta.1" "$VERSION_IM_DEPS")" != "$(printf %s\\n%s "0.9.1-beta.1" "$VERSION_IM_DEPS" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          (echo "Fail: Sort failed" && exit 1) || echo "Pass: Extensions Compatible"
+        
+        VERSION_IM_DEPS=0.9.1-alpha.1
+        # arch64
+        [ "$(printf %s\\n%s\\n "0.9.1-beta.1" "$VERSION_IM_DEPS")" != "$(printf %s\\n%s "0.9.1-beta.1" "$VERSION_IM_DEPS" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          echo "Pass: Extensions incompatible" || (echo "Fail: Extensions Compatible" && exit 1)
+
+        VERSION_IM_DEPS=0.8.1
+        # Normal Test
+        [ "$(printf %s\\n%s\\n "$VERSION_IM_DEPS" "0.8.2")" = "$(printf %s\\n%s "$VERSION_IM_DEPS" "0.8.2" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          echo "Pass: Image deps needed" || (echo "Fail: Image deps needed" && exit 1)
+        
+        VERSION_IM_DEPS=0.8.3
+        # Normal Test
+        [ "$(printf %s\\n%s\\n "$VERSION_IM_DEPS" "0.8.2")" = "$(printf %s\\n%s "$VERSION_IM_DEPS" "0.8.2" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          (echo "Fail: Image deps not needed" && exit 1) || echo "Pass: Image deps not needed"
+
+        VERSION_IM_DEPS=0.8.2
+        # Normal Test
+        [ "$(printf %s\\n%s\\n "$VERSION_IM_DEPS" "0.8.2")" = "$(printf %s\\n%s "$VERSION_IM_DEPS" "0.8.2" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          echo "Pass: Image Needed" || (echo "Fail: Image deps needed" && exit 1)
+    - name: Tensorflow Extensions - Version Based Conditions check
+      run: |
+        VERSION_TF_DEPS=0.9.1
+        # arch64
+        [ "$(printf %s\\n%s\\n "0.9.1-beta.1" "$VERSION_TF_DEPS")" != "$(printf %s\\n%s "0.9.1-beta.1" "$VERSION_TF_DEPS" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          (echo "Fail: Sort failed" && exit 1) || echo "Pass: Extensions Compatible"
+        
+        VERSION_TF_DEPS=0.9.1-rc.1
+        # arch64
+        [ "$(printf %s\\n%s\\n "0.9.1-beta.1" "$VERSION_TF_DEPS")" != "$(printf %s\\n%s "0.9.1-beta.1" "$VERSION_TF_DEPS" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          (echo "Fail: Sort failed" && exit 1) || echo "Pass: Extensions Compatible"
+        
+        VERSION_TF_DEPS=0.9.1-beta.2
+        # arch64
+        [ "$(printf %s\\n%s\\n "0.9.1-beta.1" "$VERSION_TF_DEPS")" != "$(printf %s\\n%s "0.9.1-beta.1" "$VERSION_TF_DEPS" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          (echo "Fail: Sort failed" && exit 1) || echo "Pass: Extensions Compatible"
+        
+        VERSION_TF_DEPS=0.9.1-alpha.1
+        # arch64
+        [ "$(printf %s\\n%s\\n "0.9.1-beta.1" "$VERSION_TF_DEPS")" != "$(printf %s\\n%s "0.9.1-beta.1" "$VERSION_TF_DEPS" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          echo "Pass: Extensions incompatible" || (echo "Fail: Sort failed" && exit 1)
+    - name: Latest Release Check
+      run: |
+        _res_git_=$(git ls-remote --refs --tags "https://github.com/WasmEdge/WasmEdge.git" | cut -d '/' -f 3 | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//' | grep -e '^[0-9]\+.[0-9]\+.[0-9]\+$' | tail -1)
+        _res_curl_=$(curl --silent "https://api.github.com/repos/WasmEdge/WasmEdge/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' )
+        [ "$_res_git_" = "$_res_curl_" ] && echo "Pass: Fetched version equals release" ||
+        (echo "Fail: Fetched version does not equal GitHub Ref\nFetched:$_res_git_\nCI:$_res_curl_" && exit 1)
+        
 
   macos:
     strategy:
@@ -192,3 +256,51 @@ jobs:
         # MacOS container does not have access for /usr directory
         # bash utils/install.sh -v 0.10.0-alpha.1 -p /usr
         # ls /usr/lib/wasmedge/ | grep libwasmedgePluginWasmEdgeProcess.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+    - name: Image Extensions - Version Based Conditions check
+      run: |
+        VERSION_IM_DEPS=0.10.0
+        # Darwin test
+        [ "$(printf %s\\n%s\\n "0.10.0-alpha.1" "$VERSION_IM_DEPS")" != "$(printf %s\\n%s "0.10.0-alpha.1" "$VERSION_IM_DEPS" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          (echo "Fail: Sort failed" && exit 1) || echo "Pass: Extensions Compatible"
+        
+        VERSION_IM_DEPS=0.10.0-alpha.2
+        # Darwin test
+        [ "$(printf %s\\n%s\\n "0.10.0-alpha.1" "$VERSION_IM_DEPS")" != "$(printf %s\\n%s "0.10.0-alpha.1" "$VERSION_IM_DEPS" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          (echo "Fail: Sort failed" && exit 1) || echo "Pass: Extensions Compatible"
+        
+        VERSION_IM_DEPS=0.9.1
+        # Darwin test
+        [ "$(printf %s\\n%s\\n "0.10.0-alpha.1" "$VERSION_IM_DEPS")" != "$(printf %s\\n%s "0.10.0-alpha.1" "$VERSION_IM_DEPS" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+          echo "Pass: Extensions incompatible" || (echo "Fail: Extensions Compatible"  && exit 1)
+    - name: Tensorflow Extensions - Version Based Conditions check
+      run: |
+        VERSION_TF=0.10.0-alpha.1
+        # Darwin
+        [ "$(printf %s\\n%s\\n "0.10.0-alpha.1" "$VERSION_TF")" != "$(printf %s\\n%s "0.10.0-alpha.1" "$VERSION_TF" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+        (echo "Fail: Extensions incompatible" && exit 1) || echo "Pass: Extensions compatible"
+
+        VERSION_TF=0.10.0-alpha.2
+        # Darwin
+        [ "$(printf %s\\n%s\\n "0.10.0-alpha.1" "$VERSION_TF")" != "$(printf %s\\n%s "0.10.0-alpha.1" "$VERSION_TF" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+        (echo "Fail: Extensions incompatible" && exit 1) || echo "Pass: Extensions compatible"
+
+        VERSION_TF=0.10.0-rc.1
+        # Darwin
+        [ "$(printf %s\\n%s\\n "0.10.0-alpha.1" "$VERSION_TF")" != "$(printf %s\\n%s "0.10.0-alpha.1" "$VERSION_TF" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+        (echo "Fail: Extensions incompatible" && exit 1) || echo "Pass: Extensions compatible"
+
+        VERSION_TF=0.10.0
+        # Darwin
+        [ "$(printf %s\\n%s\\n "0.10.0-alpha.1" "$VERSION_TF")" != "$(printf %s\\n%s "0.10.0-alpha.1" "$VERSION_TF" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+        (echo "Fail: Extensions incompatible" && exit 1) || echo "Pass: Extensions compatible"
+
+        VERSION_TF=0.9.1
+        # Darwin
+        [ "$(printf %s\\n%s\\n "0.10.0-alpha.1" "$VERSION_TF")" != "$(printf %s\\n%s "0.10.0-alpha.1" "$VERSION_TF" | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//')" ] &&
+        echo "Pass: Extensions incompatible" || (echo "Fail: Extensions Compatible" && exit 1)
+    - name: Latest Release Check
+      run: |
+        _res_git_=$(git ls-remote --refs --tags "https://github.com/WasmEdge/WasmEdge.git" | cut -d '/' -f 3 | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//' | grep -e '^[0-9]\+.[0-9]\+.[0-9]\+$' | tail -1)
+        _res_curl_=$(curl --silent "https://api.github.com/repos/WasmEdge/WasmEdge/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' )
+        [ "$_res_git_" = "$_res_curl_" ] && echo "Pass: Fetched version equals release" ||
+        (echo "Fail: Fetched version does not equal GitHub Ref\nFetched:$_res_git_\nCI:$_res_curl_" && exit 1)
