[Utils] GitHub CI: Install script tests update
* Added tests for changes suggested in https://github.com/WasmEdge/WasmEdge/pull/523#issuecomment-952569537

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

diff --git a/.github/workflows/test-install-script.yml b/.github/workflows/test-install-script.yml
--- a/.github/workflows/test-install-script.yml
+++ b/.github/workflows/test-install-script.yml
@@ -88,6 +88,42 @@ jobs:
     - name: Uninstall WasmEdge with all extensions
       run: |
         bash utils/uninstall.sh -q -V
+    - name: Install wasmedge-image-deps with 0.8.2
+      run: |
+        echo "$(bash utils/install.sh -e image -v 0.8.2 2>&1 | tee output.log)" | grep -qE *-deps-* && echo "Pass: Deps found in 0.8.2" \
+        || echo "Failed: Deps not found in 0.8.2" && cat output.log
+    - name: Uninstall WasmEdge with Image extensions
+      run: |
+        bash utils/uninstall.sh -q -V
+    - name: Installs wasmedge-image-deps with 0.8.1
+      run: |
+        echo "$(bash utils/install.sh -e image -v 0.8.1 2>&1 | tee output.log)" | grep -qE *-deps-* && echo "Pass: Deps found in 0.8.1" \
+        || echo "Failed: Deps not found in 0.8.1" && cat output.log
+    - name: Uninstall WasmEdge with Image extensions
+      run: |
+        bash utils/uninstall.sh -q -V
+    - name: Don't install wasmedge-image-deps with 0.9.0-rc.1
+      run: |
+        echo "$(bash utils/install.sh -e image -v 0.9.0-rc.1 2>&1 | tee output.log)" | grep -qE *-deps-* && echo "Failed: Deps found in 0.9.0-rc.1" \
+        && cat output.log || echo "Pass: Deps not found in 0.9.0-rc.1"
+    - name: Uninstall WasmEdge with Image extensions
+      run: |
+        bash utils/uninstall.sh -q -V
+    - name: No Tensorflow tools from 0.9.0-rc.1
+      run: |
+        echo "$(bash utils/install.sh -e tf -v 0.9.0-rc.1 2>&1 | tee output.log)" | grep -qE *-tools-* && echo "Failed: tools found in 0.9.0-rc.1" \
+        && cat output.log || echo "Pass: tools not found in 0.9.0-rc.1"
+    - name: Uninstall WasmEdge
+      run: |
+        bash utils/uninstall.sh -q -V
+    - name: Install versions multiple times
+      run: |
+        bash utils/install.sh -e all -V
+        bash utils/install.sh -e all -v 0.9.0-rc.1 -V
+        bash utils/install.sh -e all -v 0.8.1 -V
+    - name: Uninstall WasmEdge with Image extensions
+      run: |
+        bash utils/uninstall.sh -q -V
 
   macos:
     strategy:
