[Installer] enable pre-built noavx ggml plugin on Ubuntu 20.04
Signed-off-by: hydai <hydai@secondstate.io>
Signed-off-by: hydai <z54981220@gmail.com>

diff --git a/.github/workflows/test-installer-v2.yml b/.github/workflows/test-installer-v2.yml
--- a/.github/workflows/test-installer-v2.yml
+++ b/.github/workflows/test-installer-v2.yml
@@ -57,6 +57,12 @@ jobs:
         # It should uninstall the previous installation and install WasmEdge and the GGML plugin again
         bash utils/install_v2.sh -V
         ls ~/.wasmedge/plugin/ | grep libwasmedgePluginWasiNN.so && echo "Pass: WASI_NN-ggml Plugin found" || (echo "Fail: WASI_NN-ggml not found" && exit 1)
+    - name: Run installer-v2 with noavx option
+      if: ${{ matrix.docker_image == 'ubuntu:20.04' }}
+      run: |
+        # It will install WasmEdge and the noavx GGML plugin
+        bash utils/install_v2.sh -V --noavx
+        ls ~/.wasmedge/plugin/ | grep libwasmedgePluginWasiNN.so && echo "Pass: WASI_NN-ggml Plugin found" || (echo "Fail: WASI_NN-ggml not found" && exit 1)
     - name: Uninstall WasmEdge
       run: |
         bash utils/uninstall.sh -q -V
