[Utils] Installer CI: Install python from source as ubuntu packages are not same in all ubuntu versions
Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

diff --git a/.github/workflows/test-install-script.yml b/.github/workflows/test-install-script.yml
--- a/.github/workflows/test-install-script.yml
+++ b/.github/workflows/test-install-script.yml
@@ -27,7 +27,6 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python-version: ['2.7', '3.7', '3.8', '3.9', '3.10']
         include:
           - name: CentOS 8 Stream
             host_runner: ubuntu-latest
@@ -49,10 +48,10 @@ jobs:
             host_runner: ubuntu-latest
             package_manager: apt
             docker_image: ubuntu:16.04
-          # - name: manylinux2014 aarch64
-          #   host_runner: ARM64
-          #   package_manager: yum
-          #   docker_image: wasmedge/wasmedge:manylinux2014_aarch64
+          - name: manylinux2014 aarch64
+            host_runner: ARM64
+            package_manager: yum
+            docker_image: wasmedge/wasmedge:manylinux2014_aarch64
     name: ${{ matrix.name }}
     runs-on: ${{ matrix.host_runner }}
     container:
@@ -62,44 +61,58 @@ jobs:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ matrix.python-version }}
-        architecture: x64
-      
-    - name: Display Python version
-      run: python --version
 
     - name: Install git
       run: |
         ${{ matrix.package_manager }} update -y
-        ${{ matrix.package_manager }} install -y git libc6
-        ${{ matrix.package_manager }} upgrade -y
+        ${{ matrix.package_manager }} install -y wget git make gcc autoconf
+        version=2.7.13
+        wget https://www.python.org/ftp/python/$version/Python-$version.tgz
+        tar -xvf Python-$version.tgz
+        cd Python-$version
+        ./configure
+        make -j
+        make install
+        cd ..
+        version=3.7.13
+        wget https://www.python.org/ftp/python/$version/Python-$version.tgz
+        tar -xvf Python-$version.tgz
+        cd Python-$version
+        ./configure
+        make -j
+        make install
+        cd ..
     - name: Install WasmEdge latest release
       run: |
-        python utils/install.py -D
+        python2 utils/install.py -D
+        python3 utils/install.py -D
     - name: Uninstall WasmEdge
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install WasmEdge latest release with all extensions
       run: |
-        python utils/install.py -e all -D
+        python2 utils/install.py -e all -D
+        python3 utils/install.py -e all -D
     - name: Uninstall WasmEdge with all extensions
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install WasmEdge specific release (0.8.2)
       run: |
-        python utils/install.py -v 0.8.2 -D
+        python2 utils/install.py -v 0.8.2 -D
+        python3 utils/install.py -v 0.8.2 -D
     - name: Uninstall WasmEdge
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install WasmEdge specific release (0.8.2) with all extensions
       run: |
-        python utils/install.py -e all -v 0.8.2 -D
+        python2 utils/install.py -e all -v 0.8.2 -D
+        python3 utils/install.py -e all -v 0.8.2 -D
     - name: Install WasmEdge and test for arm extension installation
       run: |
-        python utils/install.py -e all --version=0.9.1-beta.1 \
+        python2 utils/install.py -e all --version=0.9.1-beta.1 \
+        --tf-version=0.9.1-beta.1 --tf-deps-version=0.9.1-beta.1  --tf-tools-version=0.9.1-beta.1  \
+        --image-version=0.9.1-beta.1 --image-deps-version=0.9.1-beta.1 -D
+        python3 utils/install.py -e all --version=0.9.1-beta.1 \
         --tf-version=0.9.1-beta.1 --tf-deps-version=0.9.1-beta.1  --tf-tools-version=0.9.1-beta.1  \
         --image-version=0.9.1-beta.1 --image-deps-version=0.9.1-beta.1 -D
     - name: Uninstall WasmEdge with all extensions
@@ -107,53 +120,76 @@ jobs:
         bash utils/uninstall.sh -q -V
     - name: Install wasmedge-image-deps with 0.8.2
       run: |
-        echo "$(python utils/install.py -e image -v 0.8.2 --image-version 0.8.2 --image-deps-version 0.8.2 -D 2>&1 | tee output.log)" | grep -qE "Installing image deps" && echo "Pass: Deps found in 0.8.2" \
+        echo "$(python2 utils/install.py -e image -v 0.8.2 --image-version 0.8.2 --image-deps-version 0.8.2 -D 2>&1 | tee output.log)" | grep -qE "Installing image deps" && echo "Pass: Deps found in 0.8.2" \
+        || (echo "Failed: Deps not found in 0.8.2" && cat output.log && exit 1)
+        echo "$(python3 utils/install.py -e image -v 0.8.2 --image-version 0.8.2 --image-deps-version 0.8.2 -D 2>&1 | tee output.log)" | grep -qE "Installing image deps" && echo "Pass: Deps found in 0.8.2" \
         || (echo "Failed: Deps not found in 0.8.2" && cat output.log && exit 1)
     - name: Uninstall WasmEdge with Image extensions
       run: |
         bash utils/uninstall.sh -q -V
     - name: Installs wasmedge-image-deps with 0.8.1
       run: |
-        echo "$(python utils/install.py -e image -v 0.8.1 --image-version 0.8.1 --image-deps-version 0.8.1 2>&1 | tee output.log)" | grep -qE "Installing image deps" && echo "Pass: Deps found in 0.8.1" \
+        echo "$(python2 utils/install.py -e image -v 0.8.1 --image-version 0.8.1 --image-deps-version 0.8.1 2>&1 | tee output.log)" | grep -qE "Installing image deps" && echo "Pass: Deps found in 0.8.1" \
+        || (echo "Failed: Deps not found in 0.8.1" && cat output.log && exit 1)
+        echo "$(python3 utils/install.py -e image -v 0.8.1 --image-version 0.8.1 --image-deps-version 0.8.1 2>&1 | tee output.log)" | grep -qE "Installing image deps" && echo "Pass: Deps found in 0.8.1" \
         || (echo "Failed: Deps not found in 0.8.1" && cat output.log && exit 1)
     - name: Uninstall WasmEdge with Image extensions
       run: |
         bash utils/uninstall.sh -q -V
     - name: Don't install wasmedge-image-deps with 0.9.0-rc.1
       run: |
-        echo "$(python utils/install.py -e image -v 0.9.0-rc.1 --image-version 0.9.0-rc.1 --image-deps-version 0.9.0-rc.1 -D 2>&1 | tee output.log)" | grep -qE "Image deps not needed" \
+        echo "$(python2 utils/install.py -e image -v 0.9.0-rc.1 --image-version 0.9.0-rc.1 --image-deps-version 0.9.0-rc.1 -D 2>&1 | tee output.log)" | grep -qE "Image deps not needed" \
+        && echo "Pass: Deps not found in 0.9.0-rc.1" || (echo "Failed: Deps found in 0.9.0-rc.1" && cat output.log && exit 1)
+        echo "$(python3 utils/install.py -e image -v 0.9.0-rc.1 --image-version 0.9.0-rc.1 --image-deps-version 0.9.0-rc.1 -D 2>&1 | tee output.log)" | grep -qE "Image deps not needed" \
         && echo "Pass: Deps not found in 0.9.0-rc.1" || (echo "Failed: Deps found in 0.9.0-rc.1" && cat output.log && exit 1)
     - name: Uninstall WasmEdge with Image extensions
       run: |
         bash utils/uninstall.sh -q -V
     - name: No Tensorflow tools from 0.9.0-rc.1
       run: |
-        echo "$(python utils/install.py -e tensorflow -v 0.9.0-rc.1 --tf-version 0.9.0-rc.1 --tf-tools-version 0.9.0-rc.1 --tf-deps-version 0.9.0-rc.1 -D 2>&1 | tee output.log)" | grep -qE *-tools-* && echo "Failed: tools found in 0.9.0-rc.1" \
+        echo "$(python2 utils/install.py -e tensorflow -v 0.9.0-rc.1 --tf-version 0.9.0-rc.1 --tf-tools-version 0.9.0-rc.1 --tf-deps-version 0.9.0-rc.1 -D 2>&1 | tee output.log)" | grep -qE *-tools-* && echo "Failed: tools found in 0.9.0-rc.1" \
+        && (cat output.log && exit 1) || echo "Pass: tools not found in 0.9.0-rc.1"
+        echo "$(python3 utils/install.py -e tensorflow -v 0.9.0-rc.1 --tf-version 0.9.0-rc.1 --tf-tools-version 0.9.0-rc.1 --tf-deps-version 0.9.0-rc.1 -D 2>&1 | tee output.log)" | grep -qE *-tools-* && echo "Failed: tools found in 0.9.0-rc.1" \
         && (cat output.log && exit 1) || echo "Pass: tools not found in 0.9.0-rc.1"
     - name: Uninstall WasmEdge
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install versions multiple times
       run: |
-        python utils/install.py -e all -D
-        python utils/install.py -e all -v 0.9.0-rc.1 -D
-        python utils/install.py -e all -v 0.8.1 -D
+        python2 utils/install.py -e all -D
+        python2 utils/install.py -e all -v 0.9.0-rc.1 -D
+        python2 utils/install.py -e all -v 0.8.1 -D
+        python3 utils/install.py -e all -D
+        python3 utils/install.py -e all -v 0.9.0-rc.1 -D
+        python3 utils/install.py -e all -v 0.8.1 -D
     - name: Uninstall WasmEdge with Image extensions
       run: |
         bash utils/uninstall.sh -q -V
     - name: Uninstall WasmEdge and Source Line removal check
       run: |
-        python utils/install.py && bash utils/uninstall.sh -q
+        python2 utils/install.py && bash utils/uninstall.sh -q
+        grep -qE *.wasmedge/env* ~/.bashrc && (echo "Failed: Source Lines found" && exit 1) || echo "Pass: Source Lines Removed"
+        grep -qE *.wasmedge/env* ~/.bash_profile && (echo "Failed: Source Lines found" && exit 1) || echo "Pass: Source Lines Removed"
+        grep -qE *.wasmedge/env* ~/.profile && (echo "Failed: Source Lines found" && exit 1) || echo "Pass: Source Lines Removed"
+
+        python3 utils/install.py && bash utils/uninstall.sh -q
         grep -qE *.wasmedge/env* ~/.bashrc && (echo "Failed: Source Lines found" && exit 1) || echo "Pass: Source Lines Removed"
         grep -qE *.wasmedge/env* ~/.bash_profile && (echo "Failed: Source Lines found" && exit 1) || echo "Pass: Source Lines Removed"
         grep -qE *.wasmedge/env* ~/.profile && (echo "Failed: Source Lines found" && exit 1) || echo "Pass: Source Lines Removed"
     - name: Plugins Install check
       run: |
-        python utils/install.py -v 0.10.0-alpha.1
+        python2 utils/install.py -v 0.10.0-alpha.1
         ls ~/.wasmedge/plugin/ | grep .so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-        python utils/install.py -v 0.10.0-alpha.1 -p ~/new_wasmedge
+        python2 utils/install.py -v 0.10.0-alpha.1 -p ~/new_wasmedge
         ls ~/new_wasmedge/plugin/ | grep .so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-        python utils/install.py -v 0.10.0-alpha.1 -p /usr
+        python2 utils/install.py -v 0.10.0-alpha.1 -p /usr
+        ls /usr/lib64/wasmedge/ | grep libwasmedgePluginWasmEdgeProcess.so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+
+        python3 utils/install.py -v 0.10.0-alpha.1
+        ls ~/.wasmedge/plugin/ | grep .so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+        python3 utils/install.py -v 0.10.0-alpha.1 -p ~/new_wasmedge
+        ls ~/new_wasmedge/plugin/ | grep .so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+        python3 utils/install.py -v 0.10.0-alpha.1 -p /usr
         ls /usr/lib64/wasmedge/ | grep libwasmedgePluginWasmEdgeProcess.so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
     # - name: Image Extensions - Version Based Conditions check
     #   run: |
@@ -223,7 +259,6 @@ jobs:
   macos:
     strategy:
       matrix:
-        python-version: ['2.7', '3.7', '3.8', '3.9', '3.10']
         include:
           - name: MacOS-latest
             host_runner: macos-latest
@@ -235,11 +270,6 @@ jobs:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ matrix.python-version }}
-        architecture: x64
 
     - name: Install WasmEdge latest release
       run: |
