[Utils] Installer CI: Fix [no]image deps check for versions
Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

diff --git a/.github/workflows/test-install-script.yml b/.github/workflows/test-install-script.yml
--- a/.github/workflows/test-install-script.yml
+++ b/.github/workflows/test-install-script.yml
@@ -129,8 +129,8 @@ jobs:
     - name: Install wasmedge-image-deps with 0.8.2
       if: ${{ matrix.name != 'manylinux2014 aarch64' }}
       run: |
-        echo "$(bash utils/install.sh -e image -v 0.8.2 --image-version=0.8.2 --image-deps-version=0.8.2 2>&1 | tee output.log)" | grep -qE deps && echo "Pass: Deps found in 0.8.2" \
-        || (echo "Failed: Deps not found in 0.8.2" && cat output.log && exit 1)
+        if echo "$(bash utils/install.sh -e image -v 0.8.2 --image-version=0.8.2 --image-deps-version=0.8.2 2>&1 | tee output.log)" | grep -qE deps;then echo "Pass: Deps found in 0.8.2";\
+        else echo "Failed: Deps not found in 0.8.2" && cat output.log && exit 1; fi;
     - name: Uninstall WasmEdge with Image extensions
       if: ${{ matrix.name != 'manylinux2014 aarch64' }}
       run: |
@@ -146,8 +146,8 @@ jobs:
         bash utils/uninstall.sh -q -V
     - name: Don't install wasmedge-image-deps with 0.9.0-rc.1
       run: |
-        echo "$(bash utils/install.sh -e image -v 0.9.0-rc.1 --image-version=0.9.0-rc.1 --image-deps-version=0.9.0-rc.1 2>&1 | tee output.log)" | grep -qE deps && (echo "Failed: Deps found in 0.9.0-rc.1" \
-        && cat output.log && exit 1 || echo "Pass: Deps not found in 0.9.0-rc.1")
+        if echo "$(bash utils/install.sh -e image -v 0.9.0-rc.1 --image-version=0.9.0-rc.1 --image-deps-version=0.9.0-rc.1 2>&1 | tee output.log)" | grep -qE deps;then echo "Failed: Deps found in 0.9.0-rc.1" \
+        && cat output.log && exit 1; else echo "Pass: Deps not found in 0.9.0-rc.1"; fi;
     - name: Uninstall WasmEdge with Image extensions
       run: |
         bash utils/uninstall.sh -q -V
diff --git a/.github/workflows/test-python-install-script.yml b/.github/workflows/test-python-install-script.yml
--- a/.github/workflows/test-python-install-script.yml
+++ b/.github/workflows/test-python-install-script.yml
@@ -136,10 +136,10 @@ jobs:
     - name: Install wasmedge-image-deps with 0.8.2
       if: ${{ matrix.name != 'manylinux2014 aarch64' }}
       run: |
-        echo "$(${{ matrix.python2_ex }} utils/install.py -e image -v 0.8.2 --image-version 0.8.2 --image-deps-version 0.8.2 -D 2>&1 | tee output.log)" | grep -qE "Installing image deps" && echo "Pass: Deps found in 0.8.2" \
-        || (echo "Failed: Deps not found in 0.8.2" && cat output.log && exit 1)
-        echo "$(${{ matrix.python3_ex }} utils/install.py -e image -v 0.8.2 --image-version 0.8.2 --image-deps-version 0.8.2 -D 2>&1 | tee output.log)" | grep -qE "Installing image deps" && echo "Pass: Deps found in 0.8.2" \
-        || (echo "Failed: Deps not found in 0.8.2" && cat output.log && exit 1)
+        if echo "$(${{ matrix.python2_ex }} utils/install.py -e image -v 0.8.2 --image-version=0.8.2 --image-deps-version=0.8.2 2>&1 | tee output.log)" | grep -qE deps;then echo "Pass: Deps found in 0.8.2";\
+        else echo "Failed: Deps not found in 0.8.2" && cat output.log && exit 1; fi;
+        if echo "$(${{ matrix.python3_ex }} utils/install.py -e image -v 0.8.2 --image-version=0.8.2 --image-deps-version=0.8.2 2>&1 | tee output.log)" | grep -qE deps;then echo "Pass: Deps found in 0.8.2";\
+        else echo "Failed: Deps not found in 0.8.2" && cat output.log && exit 1; fi;
     - name: Uninstall WasmEdge with Image extensions
       if: ${{ matrix.name != 'manylinux2014 aarch64' }}
       run: |
@@ -158,10 +158,10 @@ jobs:
     - name: Don't install wasmedge-image-deps with 0.9.0-rc.1
       if: ${{ matrix.name != 'manylinux2014 aarch64' }}
       run: |
-        echo "$(${{ matrix.python2_ex }} utils/install.py -e image -v 0.9.0-rc.1 --image-version 0.9.0-rc.1 --image-deps-version 0.9.0-rc.1 -D 2>&1 | tee output.log)" | grep -qE "Image deps not needed" \
-        && echo "Pass: Deps not found in 0.9.0-rc.1" || (echo "Failed: Deps found in 0.9.0-rc.1" && cat output.log && exit 1)
-        echo "$(${{ matrix.python3_ex }} utils/install.py -e image -v 0.9.0-rc.1 --image-version 0.9.0-rc.1 --image-deps-version 0.9.0-rc.1 -D 2>&1 | tee output.log)" | grep -qE "Image deps not needed" \
-        && echo "Pass: Deps not found in 0.9.0-rc.1" || (echo "Failed: Deps found in 0.9.0-rc.1" && cat output.log && exit 1)
+        if echo "$(${{ matrix.python2_ex }} utils/install.py -e image -v 0.9.0-rc.1 --image-version=0.9.0-rc.1 --image-deps-version=0.9.0-rc.1 2>&1 | tee output.log)" | grep -qE deps;then echo "Failed: Deps found in 0.9.0-rc.1" \
+        && cat output.log && exit 1; else echo "Pass: Deps not found in 0.9.0-rc.1"; fi;
+        if echo "$(${{ matrix.python3_ex }} utils/install.py -e image -v 0.9.0-rc.1 --image-version=0.9.0-rc.1 --image-deps-version=0.9.0-rc.1 2>&1 | tee output.log)" | grep -qE deps;then echo "Failed: Deps found in 0.9.0-rc.1" \
+        && cat output.log && exit 1; else echo "Pass: Deps not found in 0.9.0-rc.1"; fi;
     - name: Uninstall WasmEdge with Image extensions
       if: ${{ matrix.name != 'manylinux2014 aarch64' }}
       run: |
