[CI] Force rm to avoid 'No such file or directory' error
Signed-off-by: hydai <z54981220@gmail.com>

diff --git a/.github/workflows/test-install-script.yml b/.github/workflows/test-install-script.yml
--- a/.github/workflows/test-install-script.yml
+++ b/.github/workflows/test-install-script.yml
@@ -186,6 +186,12 @@ jobs:
         rm -f ~/.bashrc
         bash utils/install.sh -D
         if ls -a ~ | grep .bashrc; then echo "Fail: Bashrc found" && exit 1; else echo "Pass: Bashrc not found"; fi;
+    - name: Check for bashrc generation
+      if: ${{ matrix.name == 'MacOS-arm64' }}
+      run: |
+        rm -rf ~/.zshenv
+        bash utils/install.sh -D
+        if ls -a ~ | grep .zshenv; then echo echo "Pass: zshenv found"; else "Fail: zshenv not found" && exit 1; fi;
     - name: Uninstall WasmEdge
       run: |
         bash utils/uninstall.sh -q -V
