[Utils] Installer CI: Separated CI for bash script and python script
Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

diff --git a/.github/workflows/test-install-script.yml b/.github/workflows/test-install-script.yml
--- a/.github/workflows/test-install-script.yml
+++ b/.github/workflows/test-install-script.yml
@@ -96,135 +96,83 @@ jobs:
         ${{ matrix.package_manager }} install -y ${{ matrix.python_package }}
     - name: Install WasmEdge latest release
       run: |
-        ${{ matrix.python2_ex }} utils/install.py -D
-        ${{ matrix.python3_ex }} utils/install.py -D
+        bash utils/install.sh -V
     - name: Uninstall WasmEdge
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install WasmEdge latest release with all extensions
       run: |
-        ${{ matrix.python2_ex }} utils/install.py -e all -D
-        ${{ matrix.python3_ex }} utils/install.py -e all -D
+        bash utils/install.sh -e all -V
     - name: Uninstall WasmEdge with all extensions
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install WasmEdge specific release (0.8.2)
-      if: ${{ matrix.name != 'manylinux2014 aarch64' }}
       run: |
-        ${{ matrix.python2_ex }} utils/install.py -v 0.8.2 -D
-        ${{ matrix.python3_ex }} utils/install.py -v 0.8.2 -D
+        bash utils/install.sh -v 0.8.2 -V
     - name: Uninstall WasmEdge
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install WasmEdge specific release (0.8.2) with all extensions
-      if: ${{ matrix.name != 'manylinux2014 aarch64' }}
       run: |
-        ${{ matrix.python2_ex }} utils/install.py -e all -v 0.8.2 -D
-        ${{ matrix.python3_ex }} utils/install.py -e all -v 0.8.2 -D
-    - name: Install WasmEdge with all extensions compatible with min version for all platforms
+        bash utils/install.sh -e all -v 0.8.2 -V
+    - name: Install WasmEdge and test for arm extension installation
       run: |
-        ${{ matrix.python2_ex }} utils/install.py -e all --version=0.9.1-beta.1 \
+        bash utils/install.sh -e all --version=0.9.1-beta.1 \
         --tf-version=0.9.1-beta.1 --tf-deps-version=0.9.1-beta.1  --tf-tools-version=0.9.1-beta.1  \
-        --image-version=0.9.1-beta.1 --image-deps-version=0.9.1-beta.1 -D
-        ${{ matrix.python3_ex }} utils/install.py -e all --version=0.9.1-beta.1 \
-        --tf-version=0.9.1-beta.1 --tf-deps-version=0.9.1-beta.1  --tf-tools-version=0.9.1-beta.1  \
-        --image-version=0.9.1-beta.1 --image-deps-version=0.9.1-beta.1 -D
+        --image-version=0.9.1-beta.1 --image-deps-version=0.9.1-beta.1
     - name: Uninstall WasmEdge with all extensions
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install wasmedge-image-deps with 0.8.2
-      if: ${{ matrix.name != 'manylinux2014 aarch64' }}
       run: |
-        echo "$(${{ matrix.python2_ex }} utils/install.py -e image -v 0.8.2 --image-version 0.8.2 --image-deps-version 0.8.2 -D 2>&1 | tee output.log)" | grep -qE "Installing image deps" && echo "Pass: Deps found in 0.8.2" \
-        || (echo "Failed: Deps not found in 0.8.2" && cat output.log && exit 1)
-        echo "$(${{ matrix.python3_ex }} utils/install.py -e image -v 0.8.2 --image-version 0.8.2 --image-deps-version 0.8.2 -D 2>&1 | tee output.log)" | grep -qE "Installing image deps" && echo "Pass: Deps found in 0.8.2" \
-        || (echo "Failed: Deps not found in 0.8.2" && cat output.log && exit 1)
+        echo "$(bash utils/install.sh -e image -v 0.8.2 2>&1 | tee output.log)" | grep -qE *-deps-* && echo "Pass: Deps found in 0.8.2" \
+        || echo "Failed: Deps not found in 0.8.2" && cat output.log
     - name: Uninstall WasmEdge with Image extensions
       run: |
         bash utils/uninstall.sh -q -V
     - name: Installs wasmedge-image-deps with 0.8.1
-      if: ${{ matrix.name != 'manylinux2014 aarch64' }}
       run: |
-        echo "$(${{ matrix.python2_ex }} utils/install.py -e image -v 0.8.1 --image-version 0.8.1 --image-deps-version 0.8.1 2>&1 | tee output.log)" | grep -qE "Installing image deps" && echo "Pass: Deps found in 0.8.1" \
-        || (echo "Failed: Deps not found in 0.8.1" && cat output.log && exit 1)
-        echo "$(${{ matrix.python3_ex }} utils/install.py -e image -v 0.8.1 --image-version 0.8.1 --image-deps-version 0.8.1 2>&1 | tee output.log)" | grep -qE "Installing image deps" && echo "Pass: Deps found in 0.8.1" \
-        || (echo "Failed: Deps not found in 0.8.1" && cat output.log && exit 1)
+        echo "$(bash utils/install.sh -e image -v 0.8.1 2>&1 | tee output.log)" | grep -qE *-deps-* && echo "Pass: Deps found in 0.8.1" \
+        || echo "Failed: Deps not found in 0.8.1" && cat output.log
     - name: Uninstall WasmEdge with Image extensions
       run: |
         bash utils/uninstall.sh -q -V
     - name: Don't install wasmedge-image-deps with 0.9.0-rc.1
-      if: ${{ matrix.name != 'manylinux2014 aarch64' }}
       run: |
-        echo "$(${{ matrix.python2_ex }} utils/install.py -e image -v 0.9.0-rc.1 --image-version 0.9.0-rc.1 --image-deps-version 0.9.0-rc.1 -D 2>&1 | tee output.log)" | grep -qE "Image deps not needed" \
-        && echo "Pass: Deps not found in 0.9.0-rc.1" || (echo "Failed: Deps found in 0.9.0-rc.1" && cat output.log && exit 1)
-        echo "$(${{ matrix.python3_ex }} utils/install.py -e image -v 0.9.0-rc.1 --image-version 0.9.0-rc.1 --image-deps-version 0.9.0-rc.1 -D 2>&1 | tee output.log)" | grep -qE "Image deps not needed" \
-        && echo "Pass: Deps not found in 0.9.0-rc.1" || (echo "Failed: Deps found in 0.9.0-rc.1" && cat output.log && exit 1)
+        echo "$(bash utils/install.sh -e image -v 0.9.0-rc.1 2>&1 | tee output.log)" | grep -qE *-deps-* && echo "Failed: Deps found in 0.9.0-rc.1" \
+        && cat output.log || echo "Pass: Deps not found in 0.9.0-rc.1"
     - name: Uninstall WasmEdge with Image extensions
       run: |
         bash utils/uninstall.sh -q -V
     - name: No Tensorflow tools from 0.9.0-rc.1
-      if: ${{ matrix.name != 'manylinux2014 aarch64' }}
       run: |
-        echo "$(${{ matrix.python2_ex }} utils/install.py -e tensorflow -v 0.9.0-rc.1 --tf-version 0.9.0-rc.1 --tf-tools-version 0.9.0-rc.1 --tf-deps-version 0.9.0-rc.1 -D 2>&1 | tee output.log)" | grep -qE *-tools-* && echo "Failed: tools found in 0.9.0-rc.1" \
-        && (cat output.log && exit 1) || echo "Pass: tools not found in 0.9.0-rc.1"
-        echo "$(${{ matrix.python3_ex }} utils/install.py -e tensorflow -v 0.9.0-rc.1 --tf-version 0.9.0-rc.1 --tf-tools-version 0.9.0-rc.1 --tf-deps-version 0.9.0-rc.1 -D 2>&1 | tee output.log)" | grep -qE *-tools-* && echo "Failed: tools found in 0.9.0-rc.1" \
-        && (cat output.log && exit 1) || echo "Pass: tools not found in 0.9.0-rc.1"
+        echo "$(bash utils/install.sh -e tf -v 0.9.0-rc.1 2>&1 | tee output.log)" | grep -qE *-tools-* && echo "Failed: tools found in 0.9.0-rc.1" \
+        && cat output.log || echo "Pass: tools not found in 0.9.0-rc.1"
     - name: Uninstall WasmEdge
-      if: ${{ matrix.name != 'manylinux2014 aarch64' }}
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install versions multiple times
       run: |
-        ${{ matrix.python2_ex }} utils/install.py -e all -D
-        ${{ matrix.python2_ex }} utils/install.py -e all -v 0.9.1-beta.1 -D
-        ${{ matrix.python2_ex }} utils/install.py -e all -v 0.10.0 -D
-        ${{ matrix.python3_ex }} utils/install.py -e all -D
-    - name: Uninstall WasmEdge
+        bash utils/install.sh -e all -V
+        bash utils/install.sh -e all -v 0.9.0-rc.1 -V
+        bash utils/install.sh -e all -v 0.8.1 -V
+    - name: Uninstall WasmEdge with Image extensions
       run: |
         bash utils/uninstall.sh -q -V
     - name: Uninstall WasmEdge and Source Line removal check
       run: |
-        ${{ matrix.python2_ex }} utils/install.py && bash utils/uninstall.sh -q
-        grep -qE *.wasmedge/env* ~/.bashrc && (echo "Failed: Source Lines found" && exit 1) || echo "Pass: Source Lines Removed"
-        grep -qE *.wasmedge/env* ~/.bash_profile && (echo "Failed: Source Lines found" && exit 1) || echo "Pass: Source Lines Removed"
-        grep -qE *.wasmedge/env* ~/.profile && (echo "Failed: Source Lines found" && exit 1) || echo "Pass: Source Lines Removed"
-
-        ${{ matrix.python3_ex }} utils/install.py && bash utils/uninstall.sh -q
-        grep -qE *.wasmedge/env* ~/.bashrc && (echo "Failed: Source Lines found" && exit 1) || echo "Pass: Source Lines Removed"
-        grep -qE *.wasmedge/env* ~/.bash_profile && (echo "Failed: Source Lines found" && exit 1) || echo "Pass: Source Lines Removed"
-        grep -qE *.wasmedge/env* ~/.profile && (echo "Failed: Source Lines found" && exit 1) || echo "Pass: Source Lines Removed"
+        bash utils/install.sh && bash utils/uninstall.sh -q
+        grep -qE *.wasmedge/env* ~/.bashrc && echo "Failed: Source Lines found" || echo "Pass: Source Lines Removed"
+        grep -qE *.wasmedge/env* ~/.bash_profile && echo "Failed: Source Lines found" || echo "Pass: Source Lines Removed"
+        grep -qE *.wasmedge/env* ~/.profile && echo "Failed: Source Lines found" || echo "Pass: Source Lines Removed"
     - name: Plugins Install check
       run: |
-        ${{ matrix.python2_ex }} utils/install.py -v 0.10.0-alpha.1
+        bash utils/install.sh -v 0.10.0-alpha.1
         ls ~/.wasmedge/plugin/ | grep .so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-        ${{ matrix.python2_ex }} utils/install.py -v 0.10.0-alpha.1 -p ~/new_wasmedge
+        bash utils/install.sh -v 0.10.0-alpha.1 -p ~/new_wasmedge
         ls ~/new_wasmedge/plugin/ | grep .so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-        ${{ matrix.python2_ex }} utils/install.py -v 0.10.0-alpha.1 -p /usr
-        ls /usr/lib64/wasmedge/ | grep libwasmedgePluginWasmEdgeProcess.so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-
-        ${{ matrix.python3_ex }} utils/install.py -v 0.10.0-alpha.1
-        ls ~/.wasmedge/plugin/ | grep .so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-        ${{ matrix.python3_ex }} utils/install.py -v 0.10.0-alpha.1 -p ~/new_wasmedge
-        ls ~/new_wasmedge/plugin/ | grep .so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-        ${{ matrix.python3_ex }} utils/install.py -v 0.10.0-alpha.1 -p /usr
-        ls /usr/lib64/wasmedge/ | grep libwasmedgePluginWasmEdgeProcess.so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-    - name: Externally Specified plugins install check
-      if: ${{ matrix.name != 'manylinux2014 aarch64' }}
-      run: |
-        ${{ matrix.python2_ex }} utils/install.py -v 0.10.1-alpha.1 --plugins=wasi_nn-openvino -D
-        ls ~/.wasmedge/plugin/ | grep libwasmedgePluginWasiNN.so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-        ${{ matrix.python2_ex }} utils/install.py -v 0.10.1-alpha.1 -p ~/new_wasmedge --plugins=wasi_nn-openvino -D
-        ls ~/new_wasmedge/plugin/ | grep libwasmedgePluginWasiNN.so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-        ${{ matrix.python2_ex }} utils/install.py -v 0.10.1-alpha.1 -p /usr --plugins=wasi_nn-openvino -D
-        (ls /usr/lib/wasmedge/; ls /usr/lib64/wasmedge/;)2>&1 | grep libwasmedgePluginWasiNN.so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-    
-        ${{ matrix.python3_ex }} utils/install.py -v 0.10.1-alpha.1 --plugins=wasi_nn-openvino -D
-        ls ~/.wasmedge/plugin/ | grep libwasmedgePluginWasiNN.so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-        ${{ matrix.python3_ex }} utils/install.py -v 0.10.1-alpha.1 -p ~/new_wasmedge --plugins=wasi_nn-openvino -D
-        ls ~/new_wasmedge/plugin/ | grep libwasmedgePluginWasiNN.so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-        ${{ matrix.python3_ex }} utils/install.py -v 0.10.1-alpha.1 -p /usr --plugins=wasi_nn-openvino -D
-        (ls /usr/lib/wasmedge/; ls /usr/lib64/wasmedge/;)2>&1 | grep libwasmedgePluginWasiNN.so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-
+        bash utils/install.sh -v 0.10.0-alpha.1 -p /usr
+        ls /usr/lib/wasmedge/ | grep libwasmedgePluginWasmEdgeProcess.so && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
     - name: Latest Release Check
       run: |
         _res_git_=$(git ls-remote --refs --tags "https://github.com/WasmEdge/WasmEdge.git" | cut -d '/' -f 3 | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//' | grep -e '^[0-9]\+.[0-9]\+.[0-9]\+$' | tail -1)
@@ -250,41 +198,47 @@ jobs:
 
     - name: Install WasmEdge latest release
       run: |
-        python utils/install.py -D
+        bash utils/install.sh -V
     - name: Uninstall WasmEdge
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install WasmEdge latest release with all extensions
       run: |
-        python utils/install.py -e all -D
+        bash utils/install.sh -e all -V
     - name: Uninstall WasmEdge with all extensions
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install WasmEdge specific release (0.8.2)
       run: |
-        python utils/install.py -v 0.8.2 -D
+        bash utils/install.sh -v 0.8.2 -V
     - name: Uninstall WasmEdge
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install WasmEdge specific release (0.8.2) with all extensions
       run: |
-        python utils/install.py -e all -v 0.8.2 -D
+        bash utils/install.sh -e all -v 0.8.2 -V
     - name: Uninstall WasmEdge with all extensions
       run: |
         bash utils/uninstall.sh -q -V
     - name: Plugins Install check
       run: |
-        python utils/install.py -v 0.10.0-alpha.1
+        bash utils/install.sh -v 0.10.0-alpha.1
         ls ~/.wasmedge/plugin/ | grep .dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-        python utils/install.py -v 0.10.0-alpha.1 -p ~/new_wasmedge
+        bash utils/install.sh -v 0.10.0-alpha.1 -p ~/new_wasmedge
         ls ~/new_wasmedge/plugin/ | grep .dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
         # MacOS container does not have access for /usr directory
-        # python utils/install.py -v 0.10.0-alpha.1 -p /usr
-        # ls /usr/lib64/wasmedge/ | grep libwasmedgePluginWasmEdgeProcess.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-
+        # bash utils/install.sh -v 0.10.0-alpha.1 -p /usr
+        # ls /usr/lib/wasmedge/ | grep libwasmedgePluginWasmEdgeProcess.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
     - name: Latest Release Check
       run: |
         _res_git_=$(git ls-remote --refs --tags "https://github.com/WasmEdge/WasmEdge.git" | cut -d '/' -f 3 | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//' | grep -e '^[0-9]\+.[0-9]\+.[0-9]\+$' | tail -1)
         _res_curl_=$(curl --silent "https://api.github.com/repos/WasmEdge/WasmEdge/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' )
         [ "$_res_git_" = "$_res_curl_" ] && echo "Pass: Fetched version equals release" ||
         (echo "Fail: Fetched version does not equal GitHub Ref\nFetched:$_res_git_\nCI:$_res_curl_" && exit 1)
+
+    # - name: Ignore brew option check
+    #   run: |
+    #     NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
+    #     echo $(bash utils/install.sh -V) | grep "Brew is required" && echo "Pass:It requires brew" ||
+    #       echo "Fail:It should exit with error"
+    #     bash utils/install.sh -V --ignore-brew
