[Utils] Installer CI: Add checks for libtensorflow_cc
- Reference: https://github.com/WasmEdge/WasmEdge/issues/2180

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

diff --git a/.github/workflows/test-install-script.yml b/.github/workflows/test-install-script.yml
--- a/.github/workflows/test-install-script.yml
+++ b/.github/workflows/test-install-script.yml
@@ -172,6 +172,13 @@ jobs:
         grep -qE *.wasmedge/env* ~/.bashrc && echo "Failed: Source Lines found" || echo "Pass: Source Lines Removed"
         grep -qE *.wasmedge/env* ~/.bash_profile && echo "Failed: Source Lines found" || echo "Pass: Source Lines Removed"
         grep -qE *.wasmedge/env* ~/.profile && echo "Failed: Source Lines found" || echo "Pass: Source Lines Removed"
+    - name: Tensorflow changes - libtensorflow_cc.so.2.6.0 will replace the old libtensorflow.so.2.6.0
+      run: |
+        bash utils/install.sh -v 0.12.0-alpha.1 -e tensorflow --tf-version 0.12.0-alpha.1 --tf-deps-version 0.12.0-alpha.1 --tf-tools-version 0.12.0-alpha.1
+        ls ~/.wasmedge/lib/ | grep libtensorflow_cc* && echo "Pass: libtensorflow_cc found" || (echo "Fail: libtensorflow_cc found not found" && exit 1)
+    - name: Uninstall WasmEdge
+      run: |
+        bash utils/uninstall.sh -q -V
     - name: Plugins Install check
       run: |
         bash utils/install.sh -v 0.10.0-alpha.1
@@ -236,6 +243,13 @@ jobs:
         # MacOS container does not have access for /usr directory
         # bash utils/install.sh -v 0.10.0-alpha.1 -p /usr
         # ls /usr/lib/wasmedge/ | grep libwasmedgePluginWasmEdgeProcess.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+    - name: Tensorflow changes - libtensorflow_cc.so.2.6.0 will replace the old libtensorflow.so.2.6.0
+      run: |
+        bash utils/install.sh -v 0.12.0-alpha.1 -e tensorflow --tf-version 0.12.0-alpha.1 --tf-deps-version 0.12.0-alpha.1 --tf-tools-version 0.12.0-alpha.1
+        ls ~/.wasmedge/lib/ | grep libtensorflow_cc* && echo "Pass: libtensorflow_cc found" || (echo "Fail: libtensorflow_cc found not found" && exit 1)
+    - name: Uninstall WasmEdge
+      run: |
+        bash utils/uninstall.sh -q -V
     - name: Latest Release Check
       run: |
         _res_git_=$(git ls-remote --refs --tags "https://github.com/WasmEdge/WasmEdge.git" | cut -d '/' -f 3 | awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | sort --version-sort | sed 's/_$//' | grep -e '^[0-9]\+.[0-9]\+.[0-9]\+$' | tail -1)
