[Utils] Uninstall Script: Fix source statement removal
* Suggestions from https://github.com/WasmEdge/WasmEdge/issues/946#issue-1088600259
* Creates a backup of shell config incase of misshap with extension .wasmedge_backup
* Added GitHub CI test for the above addition

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

diff --git a/.github/workflows/test-install-script.yml b/.github/workflows/test-install-script.yml
--- a/.github/workflows/test-install-script.yml
+++ b/.github/workflows/test-install-script.yml
@@ -124,6 +124,10 @@ jobs:
     - name: Uninstall WasmEdge with Image extensions
       run: |
         bash utils/uninstall.sh -q -V
+    - name: Uninstall WasmEdge and Source Line removal check
+      run: |
+        bash utils/install.sh && bash utils/uninstall.sh -q
+        grep -qE *.wasmedge/env* ~/.bashrc && echo "Failed: Source Lines found" || echo "Pass: Source Lines Removed"
 
   macos:
     strategy:
