[Utils] Installer: Fix removal of header files if installed in default directory with tensorflow extension
- Ref - https://github.com/WasmEdge/WasmEdge/issues/2191#issue-1511037921
- Trivial: Fix incorrect pass to fail in CI

Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

diff --git a/.github/workflows/test-install-script.yml b/.github/workflows/test-install-script.yml
--- a/.github/workflows/test-install-script.yml
+++ b/.github/workflows/test-install-script.yml
@@ -221,7 +221,7 @@ jobs:
     - name: Check for bashrc generation
       run: |
         bash utils/install.sh -D
-        ls -a ~ | grep .bashrc && (echo "Pass: Bashrc found" && exit 1) || (echo "Pass: Bashrc not found")
+        ls -a ~ | grep .bashrc && (echo "Fail: Bashrc found" && exit 1) || (echo "Pass: Bashrc not found")
     - name: Uninstall WasmEdge
       run: |
         bash utils/uninstall.sh -q -V
