[Utils] Installer CI: Fix macOS-arm64 tests
Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

diff --git a/.github/workflows/test-install-script.yml b/.github/workflows/test-install-script.yml
--- a/.github/workflows/test-install-script.yml
+++ b/.github/workflows/test-install-script.yml
@@ -184,17 +184,26 @@ jobs:
       run: |
         bash utils/uninstall.sh -q -V
     - name: Check for bashrc generation
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |
         rm ~/.bashrc
         bash utils/install.sh -D
         if ls -a ~ | grep .bashrc; then echo "Fail: Bashrc found" && exit 1; else echo "Pass: Bashrc not found"; fi;
+    - name: Check for bashrc generation
+      if: ${{ matrix.name == 'MacOS-arm64' }}
+      run: |
+        rm ~/.zshenv
+        bash utils/install.sh -D
+        if ls -a ~ | grep .zshenv; then echo echo "Pass: zshenv found"; else "Fail: zshenv not found" && exit 1; fi;
     - name: Uninstall WasmEdge
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install WasmEdge latest release with all extensions
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |
         bash utils/install.sh -e all -D
     - name: Uninstall WasmEdge with all extensions
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install deprecated WasmEdge specific release (0.10.0)
@@ -204,21 +213,43 @@ jobs:
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install WasmEdge specific release (0.10.0) with all extensions
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |
         bash utils/install.sh -e all -v 0.10.0 -D
     - name: Uninstall WasmEdge with all extensions
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |
         bash utils/uninstall.sh -q -V
-    - name: Plugins Install check
+    - name: Plugins Install check MacOS-x86
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |
         bash utils/install.sh -v 0.10.0-alpha.1
         ls ~/.wasmedge/plugin/ | grep .dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+        bash utils/install.sh -v 0.13.1 --plugins wasmedge_tensorflow
+        ls ~/.wasmedge/plugin/ | grep libwasmedgePluginWasmEdgeTensorflow.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+        bash utils/install.sh -v 0.13.1 --plugins wasmedge_tensorflowlite
+        ls ~/.wasmedge/plugin/ | grep libwasmedgePluginWasmEdgeTensorflowLite.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
         bash utils/install.sh -v 0.10.0-alpha.1 -p ~/new_wasmedge
         ls ~/new_wasmedge/plugin/ | grep .dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
         # MacOS container does not have access for /usr directory
         # bash utils/install.sh -v 0.10.0-alpha.1 -p /usr
         # ls /usr/lib/wasmedge/ | grep libwasmedgePluginWasmEdgeProcess.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+    
+    # macos-arm64 does not have plugins
+    # - name: Plugins Install check MacOS-arm64
+    #   if: ${{ matrix.name == 'MacOS-arm64' }}
+    #   run: |
+    #     bash utils/install.sh -v 0.13.1
+    #     ls ~/.wasmedge/plugin/ | grep .dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+    #     bash utils/install.sh -v 0.13.1 --plugins wasmedge_tensorflow
+    #     ls ~/.wasmedge/plugin/ | grep libwasmedgePluginWasmEdgeTensorflow.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+    #     bash utils/install.sh -v 0.13.1 --plugins wasmedge_tensorflowlite
+    #     ls ~/.wasmedge/plugin/ | grep libwasmedgePluginWasmEdgeTensorflowLite.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+    #     bash utils/install.sh -v 0.13.1 -p ~/new_wasmedge
+    #     ls ~/new_wasmedge/plugin/ | grep .dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+
     - name: Tensorflow changes - libtensorflow_cc 2.6.0 will replace the old libtensorflow 2.6.0
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |
         bash utils/install.sh -v 0.12.0-alpha.2 -e tensorflow --tf-version 0.12.0-alpha.2 --tf-deps-version 0.12.0-alpha.2 --tf-tools-version 0.12.0-alpha.2
         ls ~/.wasmedge/lib/ | grep libtensorflow_cc* && echo "Pass: libtensorflow_cc found" || (echo "Fail: libtensorflow_cc found not found" && exit 1)
diff --git a/.github/workflows/test-python-install-script.yml b/.github/workflows/test-python-install-script.yml
--- a/.github/workflows/test-python-install-script.yml
+++ b/.github/workflows/test-python-install-script.yml
@@ -305,9 +305,11 @@ jobs:
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install WasmEdge latest release with all extensions
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |
         python3 utils/install.py -e all -D
     - name: Uninstall WasmEdge with all extensions
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |
         bash utils/uninstall.sh -q -V
     - name: Install WasmEdge specific release (0.10.0)
@@ -321,18 +323,21 @@ jobs:
         python3 utils/install.py -v 0.9.0 -D 2>&1 | grep -q "Version not supported. Min Version: 0.10.0" && echo "Pass: Version not supported. Min Version: 0.10.0 found" \
           || (echo "Failed: Version not supported. Min Version: 0.10.0 message not found" && exit 1)
     - name: Install WasmEdge specific release (0.10.0) with all extensions
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |
         python3 utils/install.py -e all -v 0.10.0 -D
     - name: Uninstall WasmEdge with all extensions
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |
         bash utils/uninstall.sh -q -V
-    - name: Plugins Install check
+    - name: Plugins Install check MacOS-x86
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |
         python3 utils/install.py -v 0.10.0-alpha.1
         ls ~/.wasmedge/plugin/ | grep .dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-        python3 utils/install.py -v 0.13.0 --plugins wasmedge_tensorflow
+        python3 utils/install.py -v 0.13.1 --plugins wasmedge_tensorflow
         ls ~/.wasmedge/plugin/ | grep libwasmedgePluginWasmEdgeTensorflow.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
-        python3 utils/install.py -v 0.13.0 --plugins wasmedge_tensorflowlite
+        python3 utils/install.py -v 0.13.1 --plugins wasmedge_tensorflowlite
         ls ~/.wasmedge/plugin/ | grep libwasmedgePluginWasmEdgeTensorflowLite.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
         python3 utils/install.py -v 0.10.0-alpha.1 -p ~/new_wasmedge
         ls ~/new_wasmedge/plugin/ | grep .dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
@@ -340,16 +345,43 @@ jobs:
         # python3 utils/install.py -v 0.10.0-alpha.1 -p /usr
         # ls /usr/lib/wasmedge/ | grep libwasmedgePluginWasmEdgeProcess.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
 
+    # macos-arm64 does not have plugins
+    # - name: Plugins Install check MacOS-arm64
+    #   if: ${{ matrix.name == 'MacOS-arm64' }}
+    #   run: |
+    #     python3 utils/install.py -v 0.13.1
+    #     ls ~/.wasmedge/plugin/ | grep .dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+    #     python3 utils/install.py -v 0.13.1 --plugins wasmedge_tensorflow
+    #     ls ~/.wasmedge/plugin/ | grep libwasmedgePluginWasmEdgeTensorflow.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+    #     python3 utils/install.py -v 0.13.1 --plugins wasmedge_tensorflowlite
+    #     ls ~/.wasmedge/plugin/ | grep libwasmedgePluginWasmEdgeTensorflowLite.dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+    #     python3 utils/install.py -v 0.13.1 -p ~/new_wasmedge
+    #     ls ~/new_wasmedge/plugin/ | grep .dylib && echo "Pass: Plugins found" || (echo "Fail: Plugins not found" && exit 1)
+
     - name: Install multiple versions and Tensorflow extension/plugins for pre and post 0.13.x
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |
         python3 utils/install.py -e tensorflow -D  2>&1 -v 0.12.0
-        python3 utils/install.py --plugins wasmedge_tensorflow -D  2>&1 -v 0.13.0
-        python3 utils/install.py --plugins wasmedge_tensorflow -D  2>&1 
+        python3 utils/install.py --plugins wasmedge_tensorflow -D  2>&1 -v 0.13.1
+        python3 utils/install.py --plugins wasmedge_tensorflow -D  2>&1
+
+    - name: Install multiple versions and Tensorflow extension/plugins for pre and post 0.13.x
+      if: ${{ matrix.name == 'MacOS-arm64' }}
+      run: |
+        python3 utils/install.py --plugins wasmedge_tensorflow -D  2>&1 -v 0.13.1
+        python3 utils/install.py --plugins wasmedge_tensorflow -D  2>&1  
     
     - name: Install multiple versions and Image extension/plugins for pre and post 0.13.x
+      if: ${{ matrix.name != 'MacOS-arm64' }}
       run: |  
         python3 utils/install.py -e image -D  2>&1 -v 0.12.0
-        python3 utils/install.py --plugins wasmedge_image -D  2>&1 -v 0.13.0
+        python3 utils/install.py --plugins wasmedge_image -D  2>&1 -v 0.13.1
+        python3 utils/install.py --plugins wasmedge_image -D  2>&1
+    
+    - name: Install multiple versions and Image extension/plugins for pre and post 0.13.x
+      if: ${{ matrix.name == 'MacOS-arm64' }}
+      run: |
+        python3 utils/install.py --plugins wasmedge_image -D  2>&1 -v 0.13.1
         python3 utils/install.py --plugins wasmedge_image -D  2>&1
 
     - name: Check for differences in the installation
